### PR TITLE
Dockerfile: bump base image to alpine:3.12 and llvm8

### PR DESCRIPTION
**Pull request by ketzacoatl**
cc @psibi

### CODE REVIEW

**Comment by psibi** [comment]
Thanks for the MR!

The master branch corresponds to the docker image for ghc-8.8.3. Does bumping the version fix any issues ? 

Also, I think it's better to follow the approach present in ghc865 branch if we want to introduce new versions: https://github.com/fpco/alpine-haskell-stack/blob/ghc865/Dockerfile as it's much faster than try to compile the entirety of GHC. :-)

**Comment by ketzacoatl** [comment]
@psibi I'm not sure I understand, should that branch you reference be merged and this rebased? or do you see updates to this PR? I'm just not sure what you are looking for, thanks for clarifying.

**Comment by psibi** [comment]
Sorry, I missed your comment. We are having different branches for the different GHC we are supporting. 

So the changes should ideally go to a particular GHC version you are planning to target. Given that master branch used to correspond to GHC-8.8.3 (it tracks 8.10 now) and it also involves building the entire compiler - I'm slightly hesistant.

**Comment by psibi** [comment]
I'm clsoing this MR as the latest image uses the latest available stabe alpine.

**Pull request closed without merging**
